# Generated by Django 4.0.3 on 2022-05-27 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='recipe_category_images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsedRefreshTokens',
            fields=[
                ('refresh_token', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['refresh_token'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('instruction', models.TextField(max_length=10000, null=True)),
                ('url', models.URLField(max_length=512, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.recipecategory')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartchef.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('gtin', models.CharField(max_length=13, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('GRAM', 'GRAM'), ('KILOGRAM', 'KILOGRAM'), ('LITER', 'LITER'), ('MILLILITER', 'MILLILITER'), ('PIECE', 'PIECE')], max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.productcategory')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smartchef.productmanufacturer')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('GRAM', 'GRAM'), ('KILOGRAM', 'KILOGRAM'), ('LITER', 'LITER'), ('MILLILITER', 'MILLILITER'), ('PIECE', 'PIECE')], max_length=255)),
                ('purchased', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.household')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.recipe')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('GRAM', 'GRAM'), ('KILOGRAM', 'KILOGRAM'), ('LITER', 'LITER'), ('MILLILITER', 'MILLILITER'), ('PIECE', 'PIECE')], max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.productcategory')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.recipe')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='household',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='smartchef.user'),
        ),
        migrations.AddField(
            model_name='household',
            name='users',
            field=models.ManyToManyField(to='smartchef.user'),
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('auth_code', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.application')),
            ],
            options={
                'ordering': ['auth_code'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.FloatField()),
                ('target', models.FloatField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.household')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartchef.product')),
            ],
            options={
                'unique_together': {('household', 'product')},
            },
        ),
    ]
