# Generated by Django 4.0.3 on 2022-04-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application_ingredient_productmanufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.productcategory'),
            preserve_default=False,
        ),
    ]
