# Generated by Django 4.0.3 on 2022-04-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ingredient_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedRefreshTokens',
            fields=[
                ('refresh_token', models.CharField(editable=False, max_length=512, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['refresh_token'],
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('auth_code', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.application')),
            ],
            options={
                'ordering': ['auth_code'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.FloatField()),
                ('target', models.FloatField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.household')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
            options={
                'unique_together': {('household', 'product')},
            },
        ),
    ]
