# Generated by Django 4.0.3 on 2022-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usedrefreshtokens_authcode_householdstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedrefreshtokens',
            name='refresh_token',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
