# Generated by Django 4.0.3 on 2022-04-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usedrefreshtokens_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.recipe'),
            preserve_default=False,
        ),
    ]
