# Workflow that runs on PRs
name: Push UI

# Only run on pushs to open PRs that are in the UI folder
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "smart-chef-ui/**"
      - ".github/workflows/push-main.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: ./smart-chef-ui/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./smart-chef-ui
      - name: Build UI
        run: yarn build
        working-directory: ./smart-chef-ui
      - name: Upload Build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: smart-chef-ui/build

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: ./smart-chef-ui/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./smart-chef-ui
      - name: Lint UI
        run: yarn lint
        working-directory: ./smart-chef-ui

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: ./smart-chef-ui/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./smart-chef-ui
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: smart-chef-ui
          command: yarn e2e-ci
      - name: Rename nyc output
        run: mv smart-chef-ui/.nyc_output/out.json smart-chef-ui/.nyc_output/out-e2e.json
      - name: Component tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: smart-chef-ui
          command: yarn cypress run-ct
      - name: Merge coverage reports
        run: yarn merge-reports
        working-directory: ./smart-chef-ui
      - name: Generate coverage report
        run: yarn generate-coverage
        working-directory: ./smart-chef-ui
      - name: Upload coverage report
        uses: codecov/codecov-action@v2

  push-docker-image:
    needs: [tests, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: smart-chef-ui/build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: smart-chef-ui
          push: true
          tags: flusinerd/smart-chef-ui:latest
          file: smart-chef-ui/ci/Dockerfile
